[package]
name = "ldpc"
version = "0.1.0"
authors = ["maxtremblay <matrem@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigs = "0.1.0"
itertools = "0.9.0"
rand = "0.7.3"
sparse-bin-mat = "0.2.2"
